### PR TITLE
Added ~39k valid and working aka.ms links in json files

### PR DESCRIPTION
**Pull request by HotCakeX**

### CODE REVIEW

**Comment by HotCakeX** [comment]
Had to remove json files **in your config folder** that had `:` in their file names because Git has problem with them and wouldn't clone the repository.

**Comment by HotCakeX** [comment]
[ResultsJson.zip](https://github.com/merill/aka/files/11433660/ResultsJson.zip)

zip file containing the json files

**Comment by ofifoto** [comment]
interesting! brute force?

**Comment by HotCakeX** [comment]
> interesting! brute force?

[simple web scan :)](https://github.com/lc/gau)

**Comment by merill** [comment]
This is awesome @HotCakeX there are some awesome links here but I also noticed quite a lot of out dated links. I'm going to clean this up to remove the invalid ones and other one off links.

Also this is hitting the limits on the app. I need to update the app to be more efficient... :)

**Comment by HotCakeX** [comment]
> This is awesome @HotCakeX there are some awesome links here but I also noticed quite a lot of out dated links. I'm going to clean this up to remove the invalid ones and other one off links.
> 
> Also this is hitting the limits on the app. I need to update the app to be more efficient... :)

Thank you ^^

Oh sorry, I thought I took care of the invalid ones, the ones that would redirect to Bing website, used your function for it. I didn't check all 39k but when I randomly opened some of them, they seemed to be valid and pointing to the correct URL.

invalid ones are considered those that point to a working URL but are considered irrelevant? like by pointing to a 3rd party website etc.

**Comment by merill** [comment]
There were many where the link was being redirected to the MSLearn home page (since the actual page no longer existed) at other times it was the Microsoft home page then there were 403s, etc. Then there were heaps of links for old products (e.g. Win7/8, Visual J Sharp, Microsoft internal urls, some examples

* ypuvyy
* Win8JamWk2
* vjsharpsupportpolicy
* UKGenderPayReport

**Comment by HotCakeX** [comment]
Ah yes, those can be a bit tricky to filter out 🤞

**Pull request closed without merging**
